<?php

namespace Database\Seeders;

use App\Models\ProdutoModel;
use App\Models\CategoriaModel;
use Framework\Database\Seeder;

/**
 * ProdutoSeeder — cria 5 produtos para cada categoria.
 */
class ProdutoSeeder extends Seeder
{
    public function run(): void
    {
        $categoriaModel = new CategoriaModel();
        $produtoModel = new ProdutoModel();

        $categorias = [
            'hamburgueres' => [
                [
                    'nome' => 'Hambúrguer Clássico',
                    'slug' => 'hamburguer-classico',
                    'descricao' => 'Hambúrguer artesanal com carne bovina, queijo, alface, tomate e molho especial.',
                    'ingredientes' => 'Pão brioche, carne bovina, queijo cheddar, alface, tomate e molho especial.',
                    'imagem_url' => 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd',
                    'preco' => 24.90,
                    'preco_promocional' => null,
                    'tempo_preparo' => 15,
                    'controla_estoque' => 0,
                    'estoque' => 0,
                    'destaque' => 1,
                ],
                [
                    'nome' => 'Hambúrguer Bacon',
                    'slug' => 'hamburguer-bacon',
                    'descricao' => 'Hambúrguer com queijo cheddar, bacon crocante e molho barbecue.',
                    'ingredientes' => 'Pão brioche, carne bovina, queijo cheddar, bacon e molho barbecue.',
                    'imagem_url' => 'https://images.unsplash.com/photo-1553979459-d2229ba7433a',
                    'preco' => 29.90,
                    'preco_promocional' => 26.90,
                    'tempo_preparo' => 20,
                    'controla_estoque' => 0,
                    'estoque' => 0,
                    'destaque' => 1,
                ],
                [
                    'nome' => 'Hambúrguer Duplo',
                    'slug' => 'hamburguer-duplo',
                    'descricao' => 'Dois hambúrgueres artesanais com queijo cheddar e molho especial.',
                    'ingredientes' => 'Pão brioche, duas carnes bovinas, queijo cheddar e molho especial.',
                    'imagem_url' => 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd',
                    'preco' => 34.90,
                    'preco_promocional' => null,
                    'tempo_preparo' => 20,
                    'controla_estoque' => 0,
                    'estoque' => 0,
                    'destaque' => 0,
                ],
                [
                    'nome' => 'Smash Burger',
                    'slug' => 'smash-burger',
                    'descricao' => 'Smash burger com carne prensada na chapa e queijo derretido.',
                    'ingredientes' => 'Pão brioche, carne bovina smash, queijo cheddar e molho da casa.',
                    'imagem_url' => 'https://images.unsplash.com/photo-1561758033-d89a9ad46330',
                    'preco' => 22.90,
                    'preco_promocional' => null,
                    'tempo_preparo' => 12,
                    'controla_estoque' => 0,
                    'estoque' => 0,
                    'destaque' => 0,
                ],
                [
                    'nome' => 'Hambúrguer BBQ',
                    'slug' => 'hamburguer-bbq',
                    'descricao' => 'Hambúrguer com cebola caramelizada e molho barbecue.',
                    'ingredientes' => 'Pão brioche, carne bovina, queijo, cebola caramelizada e barbecue.',
                    'imagem_url' => 'https://images.unsplash.com/photo-1550547660-d9450f859349',
                    'preco' => 31.90,
                    'preco_promocional' => 28.90,
                    'tempo_preparo' => 18,
                    'controla_estoque' => 0,
                    'estoque' => 0,
                    'destaque' => 1,
                ],
            ],

            'pizzas' => [
                [
                    'nome' => 'Pizza Margherita',
                    'slug' => 'pizza-margherita',
                    'descricao' => 'Pizza tradicional com molho de tomate, mozzarella e manjericão.',
                    'ingredientes' => 'Massa artesanal, molho de tomate, mozzarella e manjericão.',
                    'imagem_url' => 'https://images.unsplash.com/photo-1513104890138-7c749659a591',
                    'preco' => 39.90,
                    'preco_promocional' => null,
                    'tempo_preparo' => 30,
                    'controla_estoque' => 0,
                    'estoque' => 0,
                    'destaque' => 1,
                ],
                [
                    'nome' => 'Pizza Calabresa',
                    'slug' => 'pizza-calabresa',
                    'descricao' => 'Pizza de calabresa com cebola e mozzarella.',
                    'ingredientes' => 'Massa, molho de tomate, mozzarella, calabresa e cebola.',
                    'imagem_url' => 'https://images.unsplash.com/photo-1571407970349-bc81e7e96d47',
                    'preco' => 42.90,
                    'preco_promocional' => 37.90,
                    'tempo_preparo' => 30,
                    'controla_estoque' => 0,
                    'estoque' => 0,
                    'destaque' => 1,
                ],
                [
                    'nome' => 'Pizza Quatro Queijos',
                    'slug' => 'pizza-quatro-queijos',
                    'descricao' => 'Pizza cremosa com uma combinação de quatro queijos.',
                    'ingredientes' => 'Massa, mozzarella, provolone, parmesão e gorgonzola.',
                    'imagem_url' => 'https://images.unsplash.com/photo-1571407970349-bc81e7e96d47',
                    'preco' => 46.90,
                    'preco_promocional' => null,
                    'tempo_preparo' => 35,
                    'controla_estoque' => 0,
                    'estoque' => 0,
                    'destaque' => 0,
                ],
                [
                    'nome' => 'Pizza Portuguesa',
                    'slug' => 'pizza-portuguesa',
                    'descricao' => 'Pizza com presunto, ovos, cebola e azeitonas.',
                    'ingredientes' => 'Massa, molho, mozzarella, presunto, ovos, cebola e azeitonas.',
                    'imagem_url' => 'https://images.unsplash.com/photo-1513104890138-7c749659a591',
                    'preco' => 44.90,
                    'preco_promocional' => null,
                    'tempo_preparo' => 35,
                    'controla_estoque' => 0,
                    'estoque' => 0,
                    'destaque' => 0,
                ],
                [
                    'nome' => 'Pizza de Frango com Catupiry',
                    'slug' => 'pizza-frango-catupiry',
                    'descricao' => 'Pizza de frango desfiado com requeijão cremoso.',
                    'ingredientes' => 'Massa, molho, frango desfiado, mozzarella e requeijão cremoso.',
                    'imagem_url' => 'https://images.unsplash.com/photo-1513104890138-7c749659a591',
                    'preco' => 45.90,
                    'preco_promocional' => 41.90,
                    'tempo_preparo' => 35,
                    'controla_estoque' => 0,
                    'estoque' => 0,
                    'destaque' => 1,
                ],
            ],

            'comida-japonesa' => [
                [
                    'nome' => 'Combo Sushi',
                    'slug' => 'combo-sushi',
                    'descricao' => 'Seleção de sushis variados preparados na hora.',
                    'ingredientes' => 'Arroz japonês, salmão, peixe branco, nori e gergelim.',
                    'imagem_url' => 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c',
                    'preco' => 49.90,
                    'preco_promocional' => null,
                    'tempo_preparo' => 25,
                    'controla_estoque' => 0,
                    'estoque' => 0,
                    'destaque' => 1,
                ],
                [
                    'nome' => 'Temaki de Salmão',
                    'slug' => 'temaki-de-salmao',
                    'descricao' => 'Temaki recheado com salmão fresco e arroz japonês.',
                    'ingredientes' => 'Salmão, arroz japonês, alga nori e cebolinha.',
                    'imagem_url' => 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c',
                    'preco' => 27.90,
                    'preco_promocional' => null,
                    'tempo_preparo' => 15,
                    'controla_estoque' => 0,
                    'estoque' => 0,
                    'destaque' => 0,
                ],
                [
                    'nome' => 'Sashimi de Salmão',
                    'slug' => 'sashimi-de-salmao',
                    'descricao' => 'Fatias de salmão fresco servidas com acompanhamentos.',
                    'ingredientes' => 'Salmão fresco, wasabi e gengibre.',
                    'imagem_url' => 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c',
                    'preco' => 34.90,
                    'preco_promocional' => null,
                    'tempo_preparo' => 10,
                    'controla_estoque' => 0,
                    'estoque' => 0,
                    'destaque' => 0,
                ],
                [
                    'nome' => 'Hot Roll',
                    'slug' => 'hot-roll',
                    'descricao' => 'Sushi empanado e crocante, servido quente.',
                    'ingredientes' => 'Arroz japonês, salmão, cream cheese, nori e farinha para empanar.',
                    'imagem_url' => 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c',
                    'preco' => 32.90,
                    'preco_promocional' => 29.90,
                    'tempo_preparo' => 20,
                    'controla_estoque' => 0,
                    'estoque' => 0,
                    'destaque' => 1,
                ],
                [
                    'nome' => 'Uramaki de Salmão',
                    'slug' => 'uramaki-de-salmao',
                    'descricao' => 'Uramaki de salmão com arroz por fora e recheio especial.',
                    'ingredientes' => 'Arroz japonês, salmão, nori, cream cheese e gergelim.',
                    'imagem_url' => 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c',
                    'preco' => 29.90,
                    'preco_promocional' => null,
                    'tempo_preparo' => 20,
                    'controla_estoque' => 0,
                    'estoque' => 0,
                    'destaque' => 0,
                ],
            ],

            'marmitas-pratos-feitos' => [
                [
                    'nome' => 'Marmita de Frango Grelhado',
                    'slug' => 'marmita-frango-grelhado',
                    'descricao' => 'Frango grelhado acompanhado de arroz, feijão e legumes.',
                    'ingredientes' => 'Frango, arroz, feijão, cenoura e brócolis.',
                    'imagem_url' => 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c',
                    'preco' => 22.90,
                    'preco_promocional' => null,
                    'tempo_preparo' => 20,
                    'controla_estoque' => 0,
                    'estoque' => 0,
                    'destaque' => 0,
                ],
                [
                    'nome' => 'Prato Feito de Carne',
                    'slug' => 'prato-feito-carne',
                    'descricao' => 'Carne grelhada servida com arroz, feijão, farofa e salada.',
                    'ingredientes' => 'Carne bovina, arroz, feijão, farofa e salada.',
                    'imagem_url' => 'https://images.unsplash.com/photo-1547592180-85f173990554',
                    'preco' => 26.90,
                    'preco_promocional' => null,
                    'tempo_preparo' => 25,
                    'controla_estoque' => 0,
                    'estoque' => 0,
                    'destaque' => 1,
                ],
                [
                    'nome' => 'Marmita de Strogonoff',
                    'slug' => 'marmita-strogonoff',
                    'descricao' => 'Strogonoff cremoso servido com arroz e batata palha.',
                    'ingredientes' => 'Frango, creme de leite, molho de tomate, arroz e batata palha.',
                    'imagem_url' => 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c',
                    'preco' => 24.90,
                    'preco_promocional' => 22.90,
                    'tempo_preparo' => 25,
                    'controla_estoque' => 0,
                    'estoque' => 0,
                    'destaque' => 1,
                ],
                [
                    'nome' => 'Marmita de Carne de Panela',
                    'slug' => 'marmita-carne-panela',
                    'descricao' => 'Carne de panela macia com arroz, feijão e legumes.',
                    'ingredientes' => 'Carne bovina, batata, cenoura, arroz e feijão.',
                    'imagem_url' => 'https://images.unsplash.com/photo-1547592180-85f173990554',
                    'preco' => 27.90,
                    'preco_promocional' => null,
                    'tempo_preparo' => 30,
                    'controla_estoque' => 0,
                    'estoque' => 0,
                    'destaque' => 0,
                ],
                [
                    'nome' => 'Prato Feito de Frango à Milanesa',
                    'slug' => 'prato-frango-milanesa',
                    'descricao' => 'Frango empanado com arroz, feijão e salada fresca.',
                    'ingredientes' => 'Frango, farinha de rosca, ovos, arroz, feijão e salada.',
                    'imagem_url' => 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c',
                    'preco' => 23.90,
                    'preco_promocional' => null,
                    'tempo_preparo' => 25,
                    'controla_estoque' => 0,
                    'estoque' => 0,
                    'destaque' => 0,
                ],
            ],

            'bebidas' => [
                [
                    'nome' => 'Refrigerante Lata',
                    'slug' => 'refrigerante-lata',
                    'descricao' => 'Refrigerante em lata de 350 ml.',
                    'ingredientes' => null,
                    'imagem_url' => 'https://images.unsplash.com/photo-1581006852262-e4307cf6283a',
                    'preco' => 6.00,
                    'preco_promocional' => null,
                    'tempo_preparo' => null,
                    'controla_estoque' => 1,
                    'estoque' => 100,
                    'destaque' => 0,
                ],
                [
                    'nome' => 'Água Mineral',
                    'slug' => 'agua-mineral',
                    'descricao' => 'Água mineral sem gás, garrafa de 500 ml.',
                    'ingredientes' => null,
                    'imagem_url' => 'https://images.unsplash.com/photo-1523362628745-0c100150b504',
                    'preco' => 3.50,
                    'preco_promocional' => null,
                    'tempo_preparo' => null,
                    'controla_estoque' => 1,
                    'estoque' => 100,
                    'destaque' => 0,
                ],
                [
                    'nome' => 'Suco de Laranja',
                    'slug' => 'suco-de-laranja',
                    'descricao' => 'Suco de laranja refrescante, preparado para acompanhar a refeição.',
                    'ingredientes' => 'Laranja e água, conforme a preparação.',
                    'imagem_url' => 'https://images.unsplash.com/photo-1600271886742-f049cd451bba',
                    'preco' => 8.90,
                    'preco_promocional' => null,
                    'tempo_preparo' => 5,
                    'controla_estoque' => 0,
                    'estoque' => 0,
                    'destaque' => 1,
                ],
                [
                    'nome' => 'Chá Gelado',
                    'slug' => 'cha-gelado',
                    'descricao' => 'Bebida gelada com sabor suave e refrescante.',
                    'ingredientes' => 'Chá, água e açúcar opcional.',
                    'imagem_url' => 'https://images.unsplash.com/photo-1556679343-c7306c1976bc',
                    'preco' => 7.50,
                    'preco_promocional' => null,
                    'tempo_preparo' => 3,
                    'controla_estoque' => 1,
                    'estoque' => 50,
                    'destaque' => 0,
                ],
                [
                    'nome' => 'Limonada Natural',
                    'slug' => 'limonada-natural',
                    'descricao' => 'Limonada preparada com limões frescos.',
                    'ingredientes' => 'Limão, água e açúcar opcional.',
                    'imagem_url' => 'https://images.unsplash.com/photo-1513558161293-cdaf765edfd7',
                    'preco' => 7.90,
                    'preco_promocional' => null,
                    'tempo_preparo' => 5,
                    'controla_estoque' => 0,
                    'estoque' => 0,
                    'destaque' => 0,
                ],
            ],

            'sobremesas-doces' => [
                [
                    'nome' => 'Brownie de Chocolate',
                    'slug' => 'brownie-chocolate',
                    'descricao' => 'Brownie de chocolate com interior macio e sabor intenso.',
                    'ingredientes' => 'Chocolate, farinha de trigo, ovos, manteiga e açúcar.',
                    'imagem_url' => 'https://images.unsplash.com/photo-1551024709-8f23befc6f87',
                    'preco' => 12.90,
                    'preco_promocional' => null,
                    'tempo_preparo' => null,
                    'controla_estoque' => 1,
                    'estoque' => 30,
                    'destaque' => 1,
                ],
                [
                    'nome' => 'Pudim de Leite',
                    'slug' => 'pudim-de-leite',
                    'descricao' => 'Pudim de leite condensado com calda de caramelo.',
                    'ingredientes' => 'Leite condensado, leite, ovos e açúcar.',
                    'imagem_url' => 'https://images.unsplash.com/photo-1551024709-8f23befc6f87',
                    'preco' => 9.90,
                    'preco_promocional' => null,
                    'tempo_preparo' => null,
                    'controla_estoque' => 1,
                    'estoque' => 20,
                    'destaque' => 0,
                ],
                [
                    'nome' => 'Cheesecake de Frutas Vermelhas',
                    'slug' => 'cheesecake-frutas-vermelhas',
                    'descricao' => 'Cheesecake cremoso com cobertura de frutas vermelhas.',
                    'ingredientes' => 'Cream cheese, biscoito, manteiga, açúcar e frutas vermelhas.',
                    'imagem_url' => 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad',
                    'preco' => 15.90,
                    'preco_promocional' => null,
                    'tempo_preparo' => null,
                    'controla_estoque' => 1,
                    'estoque' => 15,
                    'destaque' => 1,
                ],
                [
                    'nome' => 'Brigadeiro Gourmet',
                    'slug' => 'brigadeiro-gourmet',
                    'descricao' => 'Brigadeiro artesanal com chocolate e granulado.',
                    'ingredientes' => 'Leite condensado, chocolate, manteiga e granulado.',
                    'imagem_url' => 'https://images.unsplash.com/photo-1551024709-8f23befc6f87',
                    'preco' => 4.50,
                    'preco_promocional' => null,
                    'tempo_preparo' => null,
                    'controla_estoque' => 1,
                    'estoque' => 40,
                    'destaque' => 0,
                ],
                [
                    'nome' => 'Torta de Limão',
                    'slug' => 'torta-de-limao',
                    'descricao' => 'Torta com creme de limão e cobertura suave.',
                    'ingredientes' => 'Limão, leite condensado, biscoito, manteiga e creme.',
                    'imagem_url' => 'https://images.unsplash.com/photo-1464305795204-6f5bbfc7fb81',
                    'preco' => 13.90,
                    'preco_promocional' => 11.90,
                    'tempo_preparo' => null,
                    'controla_estoque' => 1,
                    'estoque' => 15,
                    'destaque' => 0,
                ],
            ],

            'acai-sorvetes' => [
                [
                    'nome' => 'Açaí Tradicional',
                    'slug' => 'acai-tradicional',
                    'descricao' => 'Açaí cremoso servido com acompanhamentos à escolha.',
                    'ingredientes' => 'Polpa de açaí e xarope de guaraná.',
                    'imagem_url' => 'https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e',
                    'preco' => 16.90,
                    'preco_promocional' => null,
                    'tempo_preparo' => 5,
                    'controla_estoque' => 0,
                    'estoque' => 0,
                    'destaque' => 1,
                ],
                [
                    'nome' => 'Açaí com Banana',
                    'slug' => 'acai-com-banana',
                    'descricao' => 'Açaí cremoso acompanhado de banana fatiada.',
                    'ingredientes' => 'Açaí, banana e xarope de guaraná.',
                    'imagem_url' => 'https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e',
                    'preco' => 19.90,
                    'preco_promocional' => null,
                    'tempo_preparo' => 5,
                    'controla_estoque' => 0,
                    'estoque' => 0,
                    'destaque' => 1,
                ],
                [
                    'nome' => 'Açaí com Granola',
                    'slug' => 'acai-com-granola',
                    'descricao' => 'Açaí servido com granola crocante.',
                    'ingredientes' => 'Açaí, granola e xarope de guaraná.',
                    'imagem_url' => 'https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e',
                    'preco' => 18.90,
                    'preco_promocional' => null,
                    'tempo_preparo' => 5,
                    'controla_estoque' => 0,
                    'estoque' => 0,
                    'destaque' => 0,
                ],
                [
                    'nome' => 'Sundae de Chocolate',
                    'slug' => 'sundae-chocolate',
                    'descricao' => 'Sorvete cremoso com calda de chocolate.',
                    'ingredientes' => 'Sorvete, calda de chocolate e cobertura.',
                    'imagem_url' => 'https://images.unsplash.com/photo-1563805042-7684c019e1cb',
                    'preco' => 12.90,
                    'preco_promocional' => null,
                    'tempo_preparo' => 5,
                    'controla_estoque' => 1,
                    'estoque' => 20,
                    'destaque' => 0,
                ],
                [
                    'nome' => 'Milk-shake de Morango',
                    'slug' => 'milkshake-morango',
                    'descricao' => 'Milk-shake gelado com sabor de morango.',
                    'ingredientes' => 'Leite, sorvete e morango.',
                    'imagem_url' => 'https://images.unsplash.com/photo-1572490122747-3968b75cc699',
                    'preco' => 17.90,
                    'preco_promocional' => null,
                    'tempo_preparo' => 7,
                    'controla_estoque' => 0,
                    'estoque' => 0,
                    'destaque' => 1,
                ],
            ],

            'pasteis-salgados' => [
                [
                    'nome' => 'Pastel de Carne',
                    'slug' => 'pastel-de-carne',
                    'descricao' => 'Pastel crocante recheado com carne temperada.',
                    'ingredientes' => 'Massa de pastel, carne bovina, cebola e temperos.',
                    'imagem_url' => 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46',
                    'preco' => 9.90,
                    'preco_promocional' => null,
                    'tempo_preparo' => 10,
                    'controla_estoque' => 0,
                    'estoque' => 0,
                    'destaque' => 0,
                ],
                [
                    'nome' => 'Pastel de Queijo',
                    'slug' => 'pastel-de-queijo',
                    'descricao' => 'Pastel frito com recheio de queijo derretido.',
                    'ingredientes' => 'Massa de pastel e queijo mozzarella.',
                    'imagem_url' => 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46',
                    'preco' => 8.90,
                    'preco_promocional' => null,
                    'tempo_preparo' => 10,
                    'controla_estoque' => 0,
                    'estoque' => 0,
                    'destaque' => 0,
                ],
                [
                    'nome' => 'Coxinha de Frango',
                    'slug' => 'coxinha-de-frango',
                    'descricao' => 'Coxinha crocante recheada com frango desfiado.',
                    'ingredientes' => 'Massa, frango desfiado, farinha de rosca e temperos.',
                    'imagem_url' => 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46',
                    'preco' => 7.50,
                    'preco_promocional' => null,
                    'tempo_preparo' => 8,
                    'controla_estoque' => 1,
                    'estoque' => 30,
                    'destaque' => 1,
                ],
                [
                    'nome' => 'Empada de Frango',
                    'slug' => 'empada-de-frango',
                    'descricao' => 'Empada de massa amanteigada com recheio de frango.',
                    'ingredientes' => 'Farinha de trigo, manteiga, frango e temperos.',
                    'imagem_url' => 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46',
                    'preco' => 7.90,
                    'preco_promocional' => null,
                    'tempo_preparo' => null,
                    'controla_estoque' => 1,
                    'estoque' => 25,
                    'destaque' => 0,
                ],
                [
                    'nome' => 'Pastel de Pizza',
                    'slug' => 'pastel-de-pizza',
                    'descricao' => 'Pastel recheado com queijo, tomate e orégãos.',
                    'ingredientes' => 'Massa de pastel, mozzarella, tomate e orégãos.',
                    'imagem_url' => 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46',
                    'preco' => 9.50,
                    'preco_promocional' => null,
                    'tempo_preparo' => 10,
                    'controla_estoque' => 0,
                    'estoque' => 0,
                    'destaque' => 0,
                ],
            ],

            'saudavel-vegano' => [
                [
                    'nome' => 'Salada Vegana',
                    'slug' => 'salada-vegana',
                    'descricao' => 'Salada fresca com folhas, legumes e grãos.',
                    'ingredientes' => 'Alface, rúcula, tomate, cenoura, grão-de-bico e azeite.',
                    'imagem_url' => 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd',
                    'preco' => 19.90,
                    'preco_promocional' => null,
                    'tempo_preparo' => 10,
                    'controla_estoque' => 0,
                    'estoque' => 0,
                    'destaque' => 1,
                ],
                [
                    'nome' => 'Bowl de Quinoa',
                    'slug' => 'bowl-de-quinoa',
                    'descricao' => 'Bowl nutritivo com quinoa, vegetais e molho leve.',
                    'ingredientes' => 'Quinoa, pepino, tomate, cenoura e azeite.',
                    'imagem_url' => 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd',
                    'preco' => 24.90,
                    'preco_promocional' => null,
                    'tempo_preparo' => 15,
                    'controla_estoque' => 0,
                    'estoque' => 0,
                    'destaque' => 1,
                ],
                [
                    'nome' => 'Wrap Vegano',
                    'slug' => 'wrap-vegano',
                    'descricao' => 'Wrap recheado com vegetais frescos e homus.',
                    'ingredientes' => 'Tortilha, homus, alface, tomate e cenoura.',
                    'imagem_url' => 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd',
                    'preco' => 18.90,
                    'preco_promocional' => null,
                    'tempo_preparo' => 10,
                    'controla_estoque' => 0,
                    'estoque' => 0,
                    'destaque' => 0,
                ],
                [
                    'nome' => 'Hambúrguer Vegetal',
                    'slug' => 'hamburguer-vegetal',
                    'descricao' => 'Hambúrguer vegetal servido com pão e salada.',
                    'ingredientes' => 'Hambúrguer vegetal, pão, alface, tomate e molho vegano.',
                    'imagem_url' => 'https://images.unsplash.com/photo-1520072959219-c595dc870360',
                    'preco' => 23.90,
                    'preco_promocional' => null,
                    'tempo_preparo' => 15,
                    'controla_estoque' => 0,
                    'estoque' => 0,
                    'destaque' => 0,
                ],
                [
                    'nome' => 'Legumes Grelhados',
                    'slug' => 'legumes-grelhados',
                    'descricao' => 'Seleção de legumes grelhados temperados com ervas.',
                    'ingredientes' => 'Abobrinha, berinjela, cenoura, pimentão e azeite.',
                    'imagem_url' => 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd',
                    'preco' => 17.90,
                    'preco_promocional' => null,
                    'tempo_preparo' => 15,
                    'controla_estoque' => 0,
                    'estoque' => 0,
                    'destaque' => 0,
                ],
            ],

            'comida-mexicana' => [
                [
                    'nome' => 'Tacos Mexicanos',
                    'slug' => 'tacos-mexicanos',
                    'descricao' => 'Tacos recheados com carne temperada, vegetais e molho.',
                    'ingredientes' => 'Tortilhas, carne bovina, tomate, cebola e especiarias.',
                    'imagem_url' => 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47',
                    'preco' => 24.90,
                    'preco_promocional' => null,
                    'tempo_preparo' => 15,
                    'controla_estoque' => 0,
                    'estoque' => 0,
                    'destaque' => 1,
                ],
                [
                    'nome' => 'Burrito de Frango',
                    'slug' => 'burrito-de-frango',
                    'descricao' => 'Tortilha recheada com frango, arroz e vegetais.',
                    'ingredientes' => 'Tortilha, frango, arroz, feijão, tomate e queijo.',
                    'imagem_url' => 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47',
                    'preco' => 26.90,
                    'preco_promocional' => null,
                    'tempo_preparo' => 18,
                    'controla_estoque' => 0,
                    'estoque' => 0,
                    'destaque' => 1,
                ],
                [
                    'nome' => 'Nachos com Queijo',
                    'slug' => 'nachos-com-queijo',
                    'descricao' => 'Nachos crocantes servidos com molho de queijo.',
                    'ingredientes' => 'Nachos de milho, queijo, tomate e pimenta.',
                    'imagem_url' => 'https://images.unsplash.com/photo-1513456852971-30c0b8199d4d',
                    'preco' => 19.90,
                    'preco_promocional' => null,
                    'tempo_preparo' => 10,
                    'controla_estoque' => 0,
                    'estoque' => 0,
                    'destaque' => 0,
                ],
                [
                    'nome' => 'Quesadilla de Queijo',
                    'slug' => 'quesadilla-de-queijo',
                    'descricao' => 'Tortilha tostada recheada com queijo derretido.',
                    'ingredientes' => 'Tortilha de trigo, mozzarella e queijo cheddar.',
                    'imagem_url' => 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47',
                    'preco' => 21.90,
                    'preco_promocional' => null,
                    'tempo_preparo' => 12,
                    'controla_estoque' => 0,
                    'estoque' => 0,
                    'destaque' => 0,
                ],
                [
                    'nome' => 'Burrito Vegano',
                    'slug' => 'burrito-vegano',
                    'descricao' => 'Burrito vegetal com feijão, arroz, vegetais e guacamole.',
                    'ingredientes' => 'Tortilha, feijão, arroz, pimentão, tomate e guacamole.',
                    'imagem_url' => 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47',
                    'preco' => 23.90,
                    'preco_promocional' => null,
                    'tempo_preparo' => 15,
                    'controla_estoque' => 0,
                    'estoque' => 0,
                    'destaque' => 0,
                ],
            ],
        ];

        foreach ($categorias as $slugCategoria => $produtos) {
            $categoria = $categoriaModel
                ->where('slug', $slugCategoria)
                ->first();

            if (!$categoria) {
                continue;
            }

            $categoriaId = is_array($categoria)
                ? $categoria['id']
                : $categoria->id;

            foreach ($produtos as $indice => $dados) {
                $dados['categoria_id'] = $categoriaId;
                $dados['codigo'] = null;
                $dados['ativo'] = 1;
                $dados['ordem_exibicao'] = $indice + 1;

                $existente = $produtoModel
                    ->where('slug', $dados['slug'])
                    ->first();

                if ($existente) {
                    continue;
                }

                $produtoModel->create($dados);
            }
        }
    }
}
